⭕ part b

In [34]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import itertools
from sklearn import datasets, metrics, model_selection, svm
from sklearn.model_selection import GridSearchCV
from sklearn import preprocessing

In [5]:
import pandas as pd
from google.colab import files
uploaded = files.upload()


Saving q5.csv to q5 (1).csv


In [6]:
import io
df = pd.read_csv(io.BytesIO(uploaded['q5.csv']))

In [7]:
df

Mean of the integrated profile  \
0                           140.562500   
1                           102.507812   
2                           103.015625   
3                           136.750000   
4                            88.726562   
...                                ...   
17893                       136.429688   
17894                       122.554688   
17895                       119.335938   
17896                       114.507812   
17897                        57.062500   

        Standard deviation of the integrated profile  \
0                                          55.683782   
1                                          58.882430   
2                                          39.341649   
3                                          57.178449   
4                                          40.672225   
...                                              ...   
17893                                      59.847421   
17894                                      49.485605   
17895                                      59.935939   
17896                                      53.902400   
17897                                      85.797340   

        Excess kurtosis of the integrated profile  \
0                                       -0.234571   
1                                        0.465318   
2                                        0.323328   
3                                       -0.068415   
4                                        0.600866   
...                                           ...   
17893                                   -0.187846   
17894                                    0.127978   
17895                                    0.159363   
17896                                    0.201161   
17897                                    1.406391   

        Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                                -0.699648                   3.199833   
1                                -0.515088                   1.677258   
2                                 1.051164                   3.121237   
3                                -0.636238                   3.642977   
4                                 1.123492                   1.178930   
...                                    ...                        ...   
17893                            -0.738123                   1.296823   
17894                             0.323061                  16.409699   
17895                            -0.743025                  21.430602   
17896                            -0.024789                   1.946488   
17897                             0.089520                 188.306020   

        Standard deviation of the DM-SNR curve  \
0                                    19.110426   
1                                    14.860146   
2                                    21.744669   
3                                    20.959280   
4                                    11.468720   
...                                        ...   
17893                                12.166062   
17894                                44.626893   
17895                                58.872000   
17896                                13.381731   
17897                                64.712562   

        Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                                  7.975532                      74.242225   
1                                 10.576487                     127.393580   
2                                  7.735822                      63.171909   
3                                  6.896499                      53.593661   
4                                 14.269573                     252.567306   
...                                     ...                            ...   
17893                             15.450260                     285.931022   
17894                              2.945244                       8.297092   
17895        

In [8]:
len(df.dropna())

17898

In [9]:
import numpy as np
features = df.columns[0:8]
features

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve',
       ' Skewness of the DM-SNR curve'],
      dtype='object')

In [ ]:
y = np.array(df['target_class'])
x = np.array(df[features])
x = x.tolist()
y = y.tolist()
print(x)
print(y)

In [11]:
print(len(x))
print(len(y))

17898
17898


In [25]:
scaler = preprocessing.StandardScaler().fit(x)
x = scaler.transform(x)

In [26]:
x

array([[ 1.14931702,  1.33483164, -0.66956953, ..., -0.37062547,
        -0.07279778, -0.28743812],
       [-0.3341682 ,  1.80226533, -0.01178476, ..., -0.5889241 ,
         0.50442694,  0.21158145],
       [-0.31437216, -1.05332222, -0.14523256, ..., -0.23532816,
        -0.12599609, -0.39137346],
       ...,
       [ 0.3218423 ,  1.95621968, -0.2993338 , ...,  1.67156847,
        -1.28807874, -0.94133005],
       [ 0.13362759,  1.07450972, -0.26005007, ..., -0.66485697,
         0.37825656,  0.27584987],
       [-2.10576204,  5.73546965,  0.87267394, ...,  1.97154554,
        -2.19732744, -0.97105168]])

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.8,random_state=0)

In [28]:
print(x_test)

[[-0.34269573 -0.11551309 -0.23135075 ... -0.61548421  0.26560613
   0.11454169]
 [ 0.35138409  0.7622068  -0.30542223 ... -0.34166599 -0.07579997
  -0.29323244]
 [-0.08808812  1.67564256 -0.07648268 ... -0.35218699  0.22152365
  -0.0957837 ]
 ...
 [-0.10179308  0.12045944 -0.22021518 ... -0.57787117  0.03187201
  -0.10182319]
 [-0.56167045 -0.02146623  0.10900355 ... -0.50656752  0.37114258
   0.04451392]
 [-0.42187991  0.62445061 -0.22357903 ... -0.79756422  1.55702274
   1.79935803]]


In [ ]:
clf = svm.SVC(C=100, kernel='sigmoid')
clf = clf.fit(x_train, y_train)
acc = clf.score(x_test,y_test)
print('accuracy:',acc)

accuracy: 0.9191284307563378


⭕ part c

In [30]:
parameters = {'kernel':['rbf'], 'C': [1, 10, 100, 500], 'gamma': [0.1, 0.3, 0.5, 0.7, 0.9]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(x_train, y_train)
print(clf.best_params_)
acc = clf.best_estimator_.score(x_test,y_test)
print('accuracy:',acc)

{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
accuracy: 0.978280606187583


In [31]:
parameters = {'kernel':['linear'], 'C':  [1, 10, 100, 1000]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(x_train, y_train)
print(clf.best_params_)
acc = clf.best_estimator_.score(x_test,y_test)
print('accuracy:',acc)

{'C': 100, 'kernel': 'linear'}
accuracy: 0.979328165374677


In [32]:
parameters = {'kernel':['poly'], 'C': [1, 10, 100, 500], 'gamma': [0.01, 0.03, 0.05], 'degree': [2, 3, 4]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(x_train, y_train)
print(clf.best_params_)
acc = clf.best_estimator_.score(x_test,y_test)
print('accuracy:',acc)

{'C': 500, 'degree': 3, 'gamma': 0.05, 'kernel': 'poly'}
accuracy: 0.9773028842796284


In [35]:
from sklearn.metrics import classification_report, confusion_matrix
clf1 = svm.SVC(C=100, kernel='linear')
clf2 = svm.SVC(C=1, kernel='linear')
clf1.fit(x_train, y_train)
clf2.fit(x_train, y_train)
acc1 = clf1.score(x_test,y_test)
acc2 = clf2.score(x_test,y_test)
y_pre1 = clf1.predict(x_test)
conf1 = confusion_matrix(y_pre1,y_test)
y_pre2 = clf2.predict(x_test)
conf2 = confusion_matrix(y_pre2,y_test)

In [37]:
print('accuracy of model 1:', acc1)
print('accuracy of model 2:', acc2)
print('confusion matrix of model 1:')
print(conf1)
print('confusion matrix of model 2:')
print(conf2)

accuracy of model 1: 0.979328165374677
accuracy of model 2: 0.978629792583281
confusion matrix of model 1:
[[12965   233]
 [   63  1058]]
confusion matrix of model 2:
[[12966   244]
 [   62  1047]]
